spring:
  datasource:
    url: jdbc:mysql://db:3306/ecommerce
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ecommerce
    password: ecommerce312
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: redis
      port: 6379
  jwt:
    secret: ${JWT_SECRET}
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
